//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsObservableCollBuggy.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IsObservableCollBuggy.Resx.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device needs to be activated first.
        /// </summary>
        internal static string ActivateFirst {
            get {
                return ResourceManager.GetString("ActivateFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you still here?.
        /// </summary>
        internal static string AutoLogoutGreetingTitleText {
            get {
                return ResourceManager.GetString("AutoLogoutGreetingTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ll log you out in.
        /// </summary>
        internal static string AutoLogoutSecondGreetingTitleText {
            get {
                return ResourceManager.GetString("AutoLogoutSecondGreetingTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOTTOM.
        /// </summary>
        internal static string BOTTOM {
            get {
                return ResourceManager.GetString("BOTTOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Login.
        /// </summary>
        internal static string CannotLogin {
            get {
                return ResourceManager.GetString("CannotLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close the glass door(s) &amp; press OK..
        /// </summary>
        internal static string CloseGlassDoorWarningTitleText {
            get {
                return ResourceManager.GetString("CloseGlassDoorWarningTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press OK to Lower the Dome and Complete the Install..
        /// </summary>
        internal static string CompleteInstallMessage {
            get {
                return ResourceManager.GetString("CompleteInstallMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact your administrator..
        /// </summary>
        internal static string ContactYourAdmin {
            get {
                return ResourceManager.GetString("ContactYourAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not use me. I must be serviced by a certified technician..
        /// </summary>
        internal static string CriticalErrorMessageLine1TitleText {
            get {
                return ResourceManager.GetString("CriticalErrorMessageLine1TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact your XCT or Call Customer Support at 1-866-867-9799..
        /// </summary>
        internal static string CriticalErrorMessageLine2TitleText {
            get {
                return ResourceManager.GetString("CriticalErrorMessageLine2TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle is cancelled by the user..
        /// </summary>
        internal static string CycleCancelled {
            get {
                return ResourceManager.GetString("CycleCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling disinfection cycle ....
        /// </summary>
        internal static string CycleReadyPageCancellingCycleTitleText {
            get {
                return ResourceManager.GetString("CycleReadyPageCancellingCycleTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I cannot start zapping if I detect a person..
        /// </summary>
        internal static string CycleReadyPageCanNotZapIfMotionDetectedTitleText {
            get {
                return ResourceManager.GetString("CycleReadyPageCanNotZapIfMotionDetectedTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to complete..
        /// </summary>
        internal static string CycleReadyPageCompleteTitleText {
            get {
                return ResourceManager.GetString("CycleReadyPageCompleteTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue in.
        /// </summary>
        internal static string CycleReadyPageContinueInTitleText {
            get {
                return ResourceManager.GetString("CycleReadyPageContinueInTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue zapping ....
        /// </summary>
        internal static string CycleReadyPageContinueZappingTitleText {
            get {
                return ResourceManager.GetString("CycleReadyPageContinueZappingTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cycle can&apos;t be started yet.
        /// </summary>
        internal static string CycleReadyPageCycleCantBeStartedTitleText {
            get {
                return ResourceManager.GetString("CycleReadyPageCycleCantBeStartedTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selected..
        /// </summary>
        internal static string CycleReadyPageDetectedTitleText {
            get {
                return ResourceManager.GetString("CycleReadyPageDetectedTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not disturb me..
        /// </summary>
        internal static string CycleReadyPageDoNotDisturbMeTitleText {
            get {
                return ResourceManager.GetString("CycleReadyPageDoNotDisturbMeTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep up the good work.
        /// </summary>
        internal static string CycleReadyPageGoodWorkTitleText {
            get {
                return ResourceManager.GetString("CycleReadyPageGoodWorkTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m ready in.
        /// </summary>
        internal static string CycleReadyPageImReadyTitleText {
            get {
                return ResourceManager.GetString("CycleReadyPageImReadyTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave the room now..
        /// </summary>
        internal static string CycleReadyPageLeaveRoomTitleText {
            get {
                return ResourceManager.GetString("CycleReadyPageLeaveRoomTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lets finish.
        /// </summary>
        internal static string CycleReadyPageLetsFinishTitleText {
            get {
                return ResourceManager.GetString("CycleReadyPageLetsFinishTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I detected motion and stopped the cycle..
        /// </summary>
        internal static string CycleReadyPageMotionDetectedTitleText {
            get {
                return ResourceManager.GetString("CycleReadyPageMotionDetectedTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move me under another StrikeSpot..
        /// </summary>
        internal static string CycleReadyPageMoveToAnotherStrikeSpotTitleText {
            get {
                return ResourceManager.GetString("CycleReadyPageMoveToAnotherStrikeSpotTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move me under the remaining StrikeSpot..
        /// </summary>
        internal static string CycleReadyPageMoveToRemainingStrikeSpotTitleText {
            get {
                return ResourceManager.GetString("CycleReadyPageMoveToRemainingStrikeSpotTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I did not detect that you exited the room..
        /// </summary>
        internal static string CycleReadyPageNotExitedTitleText {
            get {
                return ResourceManager.GetString("CycleReadyPageNotExitedTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plug me in &amp; place the cones..
        /// </summary>
        internal static string CycleReadyPagePlugInTitleText {
            get {
                return ResourceManager.GetString("CycleReadyPagePlugInTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I detected power loss and stopped the cycle..
        /// </summary>
        internal static string CycleReadyPagePowerLossDetectedTitleText {
            get {
                return ResourceManager.GetString("CycleReadyPagePowerLossDetectedTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the green button above the screen..
        /// </summary>
        internal static string CycleReadyPagePushButtonTitleText {
            get {
                return ResourceManager.GetString("CycleReadyPagePushButtonTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I detected a remote cone stop..
        /// </summary>
        internal static string CycleReadyPageRemoteConeStopDetectedTitleText {
            get {
                return ResourceManager.GetString("CycleReadyPageRemoteConeStopDetectedTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait. Resetting firmware..
        /// </summary>
        internal static string CycleReadyPageResetFirmware {
            get {
                return ResourceManager.GetString("CycleReadyPageResetFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stand closer to me..
        /// </summary>
        internal static string CycleReadyPageStandCloserTitleText {
            get {
                return ResourceManager.GetString("CycleReadyPageStandCloserTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the cycle again then exit the room..
        /// </summary>
        internal static string CycleReadyPageStartCycleAgainTitleText {
            get {
                return ResourceManager.GetString("CycleReadyPageStartCycleAgainTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try the cycle again by pressing the green button above the screen..
        /// </summary>
        internal static string CycleReadyPageTryCycleAgainTitleText {
            get {
                return ResourceManager.GetString("CycleReadyPageTryCycleAgainTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I will start zapping after you exit..
        /// </summary>
        internal static string CycleReadyPageZapAfterExitTitleText {
            get {
                return ResourceManager.GetString("CycleReadyPageZapAfterExitTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development.
        /// </summary>
        internal static string DevelopmentServer {
            get {
                return ResourceManager.GetString("DevelopmentServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string DiagnosticPageAboutTabTitleText {
            get {
                return ResourceManager.GetString("DiagnosticPageAboutTabTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string DiagnosticPageAdbDisableTitleText {
            get {
                return ResourceManager.GetString("DiagnosticPageAdbDisableTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string DiagnosticPageAdbEnableTitleText {
            get {
                return ResourceManager.GetString("DiagnosticPageAdbEnableTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TroubleShooting.
        /// </summary>
        internal static string DiagnosticPageAdbTabTitleText {
            get {
                return ResourceManager.GetString("DiagnosticPageAdbTabTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Connection to Device via ADB.
        /// </summary>
        internal static string DiagnosticPageAdbTitleText {
            get {
                return ResourceManager.GetString("DiagnosticPageAdbTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha Value.
        /// </summary>
        internal static string DiagnosticPageAlphaTitleText {
            get {
                return ResourceManager.GetString("DiagnosticPageAlphaTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery.
        /// </summary>
        internal static string DiagnosticPageBatteryTabTitleText {
            get {
                return ResourceManager.GetString("DiagnosticPageBatteryTabTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        internal static string DiagnosticPageCancelTitleText {
            get {
                return ResourceManager.GetString("DiagnosticPageCancelTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dome.
        /// </summary>
        internal static string DiagnosticPageDomeTabTitleText {
            get {
                return ResourceManager.GetString("DiagnosticPageDomeTabTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        internal static string DiagnosticPageHeader1TitleText {
            get {
                return ResourceManager.GetString("DiagnosticPageHeader1TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics and Settings.
        /// </summary>
        internal static string DiagnosticPageHeader2TitleText {
            get {
                return ResourceManager.GetString("DiagnosticPageHeader2TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Lamp with serial number &apos;{0}&apos; already saved..
        /// </summary>
        internal static string DiagnosticPageLampExist {
            get {
                return ResourceManager.GetString("DiagnosticPageLampExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Lamp.
        /// </summary>
        internal static string DiagnosticPageLampInstall {
            get {
                return ResourceManager.GetString("DiagnosticPageLampInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lamp Pulse Count.
        /// </summary>
        internal static string DiagnosticPageLampPulseCountTitleText {
            get {
                return ResourceManager.GetString("DiagnosticPageLampPulseCountTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Lamp.
        /// </summary>
        internal static string DiagnosticPageLampRemove {
            get {
                return ResourceManager.GetString("DiagnosticPageLampRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove lamps, try again.
        /// </summary>
        internal static string DiagnosticPageLampRemoveFailure {
            get {
                return ResourceManager.GetString("DiagnosticPageLampRemoveFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove lamp successful.
        /// </summary>
        internal static string DiagnosticPageLampRemoveSuccess {
            get {
                return ResourceManager.GetString("DiagnosticPageLampRemoveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Saving new lamp failed, please try again!.
        /// </summary>
        internal static string DiagnosticPageLampSaveFailure {
            get {
                return ResourceManager.GetString("DiagnosticPageLampSaveFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New lamp is saved successfuly!.
        /// </summary>
        internal static string DiagnosticPageLampSaveSuccess {
            get {
                return ResourceManager.GetString("DiagnosticPageLampSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lamp Serial Number.
        /// </summary>
        internal static string DiagnosticPageLampSerialNumberTitleText {
            get {
                return ResourceManager.GetString("DiagnosticPageLampSerialNumberTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lamp.
        /// </summary>
        internal static string DiagnosticPageLampTabTitleText {
            get {
                return ResourceManager.GetString("DiagnosticPageLampTabTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOTH.
        /// </summary>
        internal static string DiagnosticPageLoginBothTitleText {
            get {
                return ResourceManager.GetString("DiagnosticPageLoginBothTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANUAL.
        /// </summary>
        internal static string DiagnosticPageLoginManualTitleText {
            get {
                return ResourceManager.GetString("DiagnosticPageLoginManualTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NFC.
        /// </summary>
        internal static string DiagnosticPageLoginNfcTitleText {
            get {
                return ResourceManager.GetString("DiagnosticPageLoginNfcTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string DiagnosticPageLoginTabTitleText {
            get {
                return ResourceManager.GetString("DiagnosticPageLoginTabTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Signal Strength.
        /// </summary>
        internal static string DiagnosticPageMinStrengthTitleText {
            get {
                return ResourceManager.GetString("DiagnosticPageMinStrengthTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Lamps to remove.
        /// </summary>
        internal static string DiagnosticPageNoLamps {
            get {
                return ResourceManager.GetString("DiagnosticPageNoLamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        internal static string DiagnosticPageOffTitleText {
            get {
                return ResourceManager.GetString("DiagnosticPageOffTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        internal static string DiagnosticPageOnTitleText {
            get {
                return ResourceManager.GetString("DiagnosticPageOnTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plug me in before adjusting settings..
        /// </summary>
        internal static string DiagnosticPagePlugInTitleText {
            get {
                return ResourceManager.GetString("DiagnosticPagePlugInTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse Frequency.
        /// </summary>
        internal static string DiagnosticPagePulseFrequencyTabTitleText {
            get {
                return ResourceManager.GetString("DiagnosticPagePulseFrequencyTabTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please return me to bottom before proceeding..
        /// </summary>
        internal static string DiagnosticPageReturnMotorHomeTitleText {
            get {
                return ResourceManager.GetString("DiagnosticPageReturnMotorHomeTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rfid Room Tags.
        /// </summary>
        internal static string DiagnosticPageRfidRoomTagsTitleText {
            get {
                return ResourceManager.GetString("DiagnosticPageRfidRoomTagsTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID Parameters.
        /// </summary>
        internal static string DiagnosticPageRfidTabTitleText {
            get {
                return ResourceManager.GetString("DiagnosticPageRfidTabTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rfid User Tags.
        /// </summary>
        internal static string DiagnosticPageRfidUserTagsTitleText {
            get {
                return ResourceManager.GetString("DiagnosticPageRfidUserTagsTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSSI Threshold.
        /// </summary>
        internal static string DiagnosticPageRSSIThresholdTitleText {
            get {
                return ResourceManager.GetString("DiagnosticPageRSSIThresholdTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save New Lamp.
        /// </summary>
        internal static string DiagnosticPageSaveNewLampTitleText {
            get {
                return ResourceManager.GetString("DiagnosticPageSaveNewLampTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        internal static string DiagnosticPageSaveTitleText {
            get {
                return ResourceManager.GetString("DiagnosticPageSaveTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a tab on the left.
        /// </summary>
        internal static string DiagnosticPageSelectTabTitleText {
            get {
                return ResourceManager.GetString("DiagnosticPageSelectTabTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Battery Power Relays.
        /// </summary>
        internal static string DiagnosticPageSetBatteryPowerRelaysTitleText {
            get {
                return ResourceManager.GetString("DiagnosticPageSetBatteryPowerRelaysTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Position to Move Dome.
        /// </summary>
        internal static string DiagnosticPageSetDomePositionTitleText {
            get {
                return ResourceManager.GetString("DiagnosticPageSetDomePositionTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set my Login Mode.
        /// </summary>
        internal static string DiagnosticPageSetLoginTitleText {
            get {
                return ResourceManager.GetString("DiagnosticPageSetLoginTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Pulse Frequency..
        /// </summary>
        internal static string DiagnosticPageSetPulseFrequencyTitleText {
            get {
                return ResourceManager.GetString("DiagnosticPageSetPulseFrequencyTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string DiagnosticPageStatusTabTitleText {
            get {
                return ResourceManager.GetString("DiagnosticPageStatusTabTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Wi-Fi.
        /// </summary>
        internal static string DiagnosticPageWifiTabConnectHiddenNetwork {
            get {
                return ResourceManager.GetString("DiagnosticPageWifiTabConnectHiddenNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string DiagnosticPageWifiTabDisconnect {
            get {
                return ResourceManager.GetString("DiagnosticPageWifiTabDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget.
        /// </summary>
        internal static string DiagnosticPageWifiTabForget {
            get {
                return ResourceManager.GetString("DiagnosticPageWifiTabForget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string DiagnosticPageWifiTabRefreshList {
            get {
                return ResourceManager.GetString("DiagnosticPageWifiTabRefreshList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wi-Fi.
        /// </summary>
        internal static string DiagnosticPageWifiTabTitleText {
            get {
                return ResourceManager.GetString("DiagnosticPageWifiTabTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string DiagnosticPageWifiTabWifiCancel {
            get {
                return ResourceManager.GetString("DiagnosticPageWifiTabWifiCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string DiagnosticPageWifiTabWifiConnect {
            get {
                return ResourceManager.GetString("DiagnosticPageWifiTabWifiConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type password.
        /// </summary>
        internal static string DiagnosticPageWifiTabWifiPasswordPlaceholder {
            get {
                return ResourceManager.GetString("DiagnosticPageWifiTabWifiPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter username and password to continue.
        /// </summary>
        internal static string EnterCredentials {
            get {
                return ResourceManager.GetString("EnterCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password to continue.
        /// </summary>
        internal static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your Username.
        /// </summary>
        internal static string EnterUserName {
            get {
                return ResourceManager.GetString("EnterUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXIT.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Evening.
        /// </summary>
        internal static string GreetingLabelEveningText {
            get {
                return ResourceManager.GetString("GreetingLabelEveningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Morning.
        /// </summary>
        internal static string GreetingLabelMorningText {
            get {
                return ResourceManager.GetString("GreetingLabelMorningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Afternoon.
        /// </summary>
        internal static string GreetingLabelNoonText {
            get {
                return ResourceManager.GetString("GreetingLabelNoonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        internal static string HiTitleText {
            get {
                return ResourceManager.GetString("HiTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 characters in length.
        /// </summary>
        internal static string IncorrectPasswordLength {
            get {
                return ResourceManager.GetString("IncorrectPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Lamp..
        /// </summary>
        internal static string InstalledLamp {
            get {
                return ResourceManager.GetString("InstalledLamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install the Lamp and Close the Glass Doors.
        /// </summary>
        internal static string InstallLampAndCloseDoors {
            get {
                return ResourceManager.GetString("InstallLampAndCloseDoors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install the Previous Lamp and Lower the Dome..
        /// </summary>
        internal static string InstallThePreviousLampAndLowerTheDome {
            get {
                return ResourceManager.GetString("InstallThePreviousLampAndLowerTheDome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Error.
        /// </summary>
        internal static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AtlasVersion.
        /// </summary>
        internal static string IotHubServiceAtlasVersion {
            get {
                return ResourceManager.GetString("IotHubServiceAtlasVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lamp Installation Required..
        /// </summary>
        internal static string LampInstallationRequired {
            get {
                return ResourceManager.GetString("LampInstallationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.  User did not scan a valid lamp tag..
        /// </summary>
        internal static string LampInstallationTimeoutNFC {
            get {
                return ResourceManager.GetString("LampInstallationTimeoutNFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout. User did not enter a valid serial number..
        /// </summary>
        internal static string LampInstallationTimeoutSerialInput {
            get {
                return ResourceManager.GetString("LampInstallationTimeoutSerialInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to install a lamp..
        /// </summary>
        internal static string LampManualLogin {
            get {
                return ResourceManager.GetString("LampManualLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan your badge to install a lamp..
        /// </summary>
        internal static string LampNfcLogin {
            get {
                return ResourceManager.GetString("LampNfcLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lamp Replacement Required..
        /// </summary>
        internal static string LampReplacementRequired {
            get {
                return ResourceManager.GetString("LampReplacementRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please lower the Dome to proceed..
        /// </summary>
        internal static string LowerDomeTitleText {
            get {
                return ResourceManager.GetString("LowerDomeTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press OK to lower the dome..
        /// </summary>
        internal static string LowerDomeWarningTitleText {
            get {
                return ResourceManager.GetString("LowerDomeWarningTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowering dome please wait....
        /// </summary>
        internal static string LoweringDomeTitleText {
            get {
                return ResourceManager.GetString("LoweringDomeTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your credentials to continue.
        /// </summary>
        internal static string ManualLoginInstruction {
            get {
                return ResourceManager.GetString("ManualLoginInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to start zapping..
        /// </summary>
        internal static string ManualLoginText {
            get {
                return ResourceManager.GetString("ManualLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIDDLE.
        /// </summary>
        internal static string MIDDLE {
            get {
                return ResourceManager.GetString("MIDDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string MinutesTitleText {
            get {
                return ResourceManager.GetString("MinutesTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I detect.
        /// </summary>
        internal static string MultiBadgeDetectedTitleText {
            get {
                return ResourceManager.GetString("MultiBadgeDetectedTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please scan your Badge or click Login..
        /// </summary>
        internal static string MultiLoginText {
            get {
                return ResourceManager.GetString("MultiLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple tags detected, move closer to one tag.
        /// </summary>
        internal static string MultipleRfidTagDetectedTitleText {
            get {
                return ResourceManager.GetString("MultipleRfidTagDetectedTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who is zapping?.
        /// </summary>
        internal static string MultiUserLoginTitleText {
            get {
                return ResourceManager.GetString("MultiUserLoginTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEXT.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No badges detected..
        /// </summary>
        internal static string NoBadgeDetectedTitleText {
            get {
                return ResourceManager.GetString("NoBadgeDetectedTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Lamp Installed..
        /// </summary>
        internal static string NoLampInstalled {
            get {
                return ResourceManager.GetString("NoLampInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string NotApplicable {
            get {
                return ResourceManager.GetString("NotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One badge detected..
        /// </summary>
        internal static string OneBadgeDetectedTitleText {
            get {
                return ResourceManager.GetString("OneBadgeDetectedTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only a Service User can login..
        /// </summary>
        internal static string OnlyServiceUser {
            get {
                return ResourceManager.GetString("OnlyServiceUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password can&apos;t be empty.
        /// </summary>
        internal static string PasswordEmpty {
            get {
                return ResourceManager.GetString("PasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password must contain at least 2 out of the 3 following items:\n Uppercase letters(A-Z) Numbers(0 - 9) \&quot;-\&quot; or \&quot;.\&quot; characters.
        /// </summary>
        internal static string PasswordMissingSpecialCharacters {
            get {
                return ResourceManager.GetString("PasswordMissingSpecialCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password wasn&apos;t recognized.
        /// </summary>
        internal static string PasswordNotRecognized {
            get {
                return ResourceManager.GetString("PasswordNotRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position is ready to engage..
        /// </summary>
        internal static string PositionDetectionLockedLabelText {
            get {
                return ResourceManager.GetString("PositionDetectionLockedLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get position in lock radius..
        /// </summary>
        internal static string PositionDetectionNotLockedLabelText {
            get {
                return ResourceManager.GetString("PositionDetectionNotLockedLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order for the dome to be lowered the robot must first be plugged into an AC power outlet.
        /// </summary>
        internal static string PowerPlugErrorText {
            get {
                return ResourceManager.GetString("PowerPlugErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please plug me into a power outlet to proceed..
        /// </summary>
        internal static string PowerPlugTitleText {
            get {
                return ResourceManager.GetString("PowerPlugTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        internal static string ProductionServer {
            get {
                return ResourceManager.GetString("ProductionServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulb has.
        /// </summary>
        internal static string PulseCountMessageTitleText {
            get {
                return ResourceManager.GetString("PulseCountMessageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulsing Limit Reached..
        /// </summary>
        internal static string PulseLimitReached {
            get {
                return ResourceManager.GetString("PulseLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disinfection cycle cannot be run - Bulb Requires Replacement. Call Customer Support at 1-866-867-9799..
        /// </summary>
        internal static string PulseLimitReachedMessageTitleText {
            get {
                return ResourceManager.GetString("PulseLimitReachedMessageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulsing Limit Reached.
        /// </summary>
        internal static string PulseLimitReachedTopicTitleText {
            get {
                return ResourceManager.GetString("PulseLimitReachedTopicTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pulses.
        /// </summary>
        internal static string PulsesText {
            get {
                return ResourceManager.GetString("PulsesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulb Requires Replacement Immediately. Call Customer Support at 1-866-867-9799..
        /// </summary>
        internal static string PulseWarningMessageTitleText {
            get {
                return ResourceManager.GetString("PulseWarningMessageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Lamp Warning.
        /// </summary>
        internal static string PulseWarningTopicTitleText {
            get {
                return ResourceManager.GetString("PulseWarningTopicTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raise the Dome to install the Lamp..
        /// </summary>
        internal static string RaiseDomeToInstallLamp {
            get {
                return ResourceManager.GetString("RaiseDomeToInstallLamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raise the Dome to remove the Lamp..
        /// </summary>
        internal static string RaiseDomeToRemoveLamp {
            get {
                return ResourceManager.GetString("RaiseDomeToRemoveLamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Lamp.
        /// </summary>
        internal static string RemoveLamp {
            get {
                return ResourceManager.GetString("RemoveLamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the Lamp and Lower the Dome..
        /// </summary>
        internal static string RemoveLampAndLowerDome {
            get {
                return ResourceManager.GetString("RemoveLampAndLowerDome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the Lamp..
        /// </summary>
        internal static string RemoveTheLamp {
            get {
                return ResourceManager.GetString("RemoveTheLamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to replace a lamp..
        /// </summary>
        internal static string ReplaceLampLoginManual {
            get {
                return ResourceManager.GetString("ReplaceLampLoginManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan your badge to replace a lamp..
        /// </summary>
        internal static string ReplaceLampLoginNfc {
            get {
                return ResourceManager.GetString("ReplaceLampLoginNfc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-scan your badge..
        /// </summary>
        internal static string RescanYourBadge {
            get {
                return ResourceManager.GetString("RescanYourBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Successfully Detected.
        /// </summary>
        internal static string RfidTagDetectedTitleText {
            get {
                return ResourceManager.GetString("RfidTagDetectedTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms Left on Lamp.
        /// </summary>
        internal static string RoomsLeftOnLamp {
            get {
                return ResourceManager.GetString("RoomsLeftOnLamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check there are no items in the way of the dome returning home..
        /// </summary>
        internal static string SafetyCheckMessageTitleText {
            get {
                return ResourceManager.GetString("SafetyCheckMessageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password can&apos;t be your username.
        /// </summary>
        internal static string SameUserNamePassword {
            get {
                return ResourceManager.GetString("SameUserNamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string SecondsTitleText {
            get {
                return ResourceManager.GetString("SecondsTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Room to zap..
        /// </summary>
        internal static string SelectRoom {
            get {
                return ResourceManager.GetString("SelectRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Room Selected..
        /// </summary>
        internal static string SelectRoomError {
            get {
                return ResourceManager.GetString("SelectRoomError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Room Unit to proceed. .
        /// </summary>
        internal static string SelectRoomUnit {
            get {
                return ResourceManager.GetString("SelectRoomUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Room Unit Selected..
        /// </summary>
        internal static string SelectRoomUnitError {
            get {
                return ResourceManager.GetString("SelectRoomUnitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Target Server.
        /// </summary>
        internal static string SelectServerTitleText {
            get {
                return ResourceManager.GetString("SelectServerTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Menu.
        /// </summary>
        internal static string ServerMenuTabTitleText {
            get {
                return ResourceManager.GetString("ServerMenuTabTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m logging you in ....
        /// </summary>
        internal static string SingleUserLoginTitleText {
            get {
                return ResourceManager.GetString("SingleUserLoginTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staging.
        /// </summary>
        internal static string StagingServer {
            get {
                return ResourceManager.GetString("StagingServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place me under a STRIKESPOT™....
        /// </summary>
        internal static string StrikeSpotTitleText {
            get {
                return ResourceManager.GetString("StrikeSpotTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is zapping with this robot..
        /// </summary>
        internal static string SwitchUserGreetingTitleText {
            get {
                return ResourceManager.GetString("SwitchUserGreetingTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who will continue?.
        /// </summary>
        internal static string SwitchUserHeaderMessageTitleText {
            get {
                return ResourceManager.GetString("SwitchUserHeaderMessageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOP.
        /// </summary>
        internal static string TOP {
            get {
                return ResourceManager.GetString("TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again.
        /// </summary>
        internal static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please remove and place the Black Tethered Cone to proceed..
        /// </summary>
        internal static string UnDockBlackCone {
            get {
                return ResourceManager.GetString("UnDockBlackCone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the green button above the screen to try again..
        /// </summary>
        internal static string UnknownCycleInterruptedErrorBotText {
            get {
                return ResourceManager.GetString("UnknownCycleInterruptedErrorBotText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error during the cycle.
        ///    Error Code: 40300.
        /// </summary>
        internal static string UnknownCycleInterruptedErrorTopText {
            get {
                return ResourceManager.GetString("UnknownCycleInterruptedErrorTopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Robot may only be used as part of an environmental disinfection program and any other use is expressly prohibited. This Robot may not be used in any trial, test or other evaluation without the written consent of Xenex Disinfection Services LLC..
        /// </summary>
        internal static string UserAgreement {
            get {
                return ResourceManager.GetString("UserAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USERNAME.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username doesn&apos;t exist. Enter a valid username.
        /// </summary>
        internal static string UserNameDoesNotExist {
            get {
                return ResourceManager.GetString("UserNameDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username wasn&apos;t recognized.
        /// </summary>
        internal static string UserNotRecognized {
            get {
                return ResourceManager.GetString("UserNotRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating Credentials.
        /// </summary>
        internal static string ValidatingCredentials {
            get {
                return ResourceManager.GetString("ValidatingCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please scan your badge..
        /// </summary>
        internal static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your badge does not have access..
        /// </summary>
        internal static string YourBadgeDoesNotHaveAccess {
            get {
                return ResourceManager.GetString("YourBadgeDoesNotHaveAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your badge was not recognized..
        /// </summary>
        internal static string YourBadgeWasNotRecognized {
            get {
                return ResourceManager.GetString("YourBadgeWasNotRecognized", resourceCulture);
            }
        }
    }
}
